### ISSUE TITLE
Создать пустой проект для backend

### ISSUE THREAD

**Issue by sshiae** [ITOneNorthGateVologda/.github#1]
Создать пустой проект для backend на технологиях Java, Spring

Включить такие зависимости, как `Spring Data Jpa`, `Lombok`, `Spring Web`, `Spring Security`, `PostgreSQL Driver`

Если что то забудем, то потом по факту добавим 

https://start.spring.io/

**Comment by AAKVAS** [comment]
Готов https://github.com/ITOneNorthGateVologda/backend
