### ISSUE TITLE
Описать предметную область нашего разрабатываемого решения

### ISSUE THREAD

**Issue by sshiae** [ITOneNorthGateVologda/.github#13]

**Comment by olgapshen** [comment]
Итак! Общая концепция системы бюджетов от Ворот Севера.

Ссылки:

* https://habr.com/ru/companies/timio/articles/202720/
* https://skillbox.ru/media/management/glavnoe-o-byudzhetirovanii-chto-eto-kak-ego-organizuyut-i-kakie-byvayut-byudzhety

Важная цитата из второй ссылки:

Бюджетирование помогает предсказывать результаты деятельности компании. Главная цель бюджетирования — повысить эффективность работы компании на каждом этапе.

Приложение будет иметь несколько базовых структур данных:

* Транзакция
* Фискальная запись
* Категория фискальной записи
* Счёт
* Бюджет
* Цель
* Остаток
* Неучтённые расходы
* Правила применения фискальных записей к бюджетам

Транзакция это некая покупка или начисление зарплаты. Транзакции будут храниться в буфере транзакций и являтся записью таблицы.
Транзакции совершаются по отношению к счёту. Соответственно отношение счёта к странзакциям, один ко многим,
где счетов будет множество, но каждая транзакция относится только к одному счёту. Транзакции нужно хранить отдельно от счетов, для разбития
первых на фискальные записи и "применения" последних к бюждету.

Поля транзакции:

* Сумма
* Знак (+/-)
* Счёт
* Описание

Фискальные записи это составляющие транзакции необходимые для текущей (постоянной) актуализации бюджета.
Фискальная запись определена ФЗ или иным законом каждого государства. В свете отсутствия доступа клиента к сервисам ОФД
(операторы фискальных данных), разбитие транзакции на фискальные записи будет происходить вручную. Уточним.
При поступлении транзакции, пользователь выделит из неё основные фискальные записи, которые применятся к соответствующим бюджетам.
Остаток, который не будет вычленен (нименьшая часть суммы) войдёт в структуру данных "неучтённые расходы". К каждой фискальной записи
будет применять категория, которая сможет автоматом повлиять на состояние соответствующего бюджета. Категории могут быть:

* Котейшества
* Отдых в Карелии
* Погашение кредита

Структура фискальных записей будет:

* Сумма
* Транзакция (удалённый ключ)
* Описание
* Категория

Знак фискальной записи всегда - минус.

Приведём пример. Пусть с Альфабанка пришёл список транзакций. Среди прочих были:

* Погашение кредита 5 000 р
* Покупка на 6 180 р. в Макси

Среди покупок было:

* Палатка 4 000 р
* Корм котам 2 000
* Пиво 120 р
* Хлеб 60 р

Пользователь создаёт три фискальных записи:

1. Корм котам:
    1. Описание: "Корм котам"
    3. Сумма: 2 000
    4. (соответствующая транзакция) 
    5. Категория: "Котейшества"
2. Палатка для отдыха в Карелии:
    1. Описание: "Палатка для отдыха в Карелии"
    2. Сумма: 4 000
    3. (соответствующая транзакция) 
    4. Категория: "Отдых в Карелии"
3. Погашение кредита
    1. Описание: "Погашение кредита"
    2. Сумма: 5 000
    3. (соответствующая транзакция) 
    4. Категория: "Погашение кредита"

Автоматом, через сущность: "правила применения фискальных записей к бюджетам" три фискальных записи применяются к трём бюджетам.
О самих бюджетах, счетах и правилах подробнее далее. Пока приведём список бюджетов:

1. Еженедельная закупка корма котам
    1. Цель: Еженедельная закупка корма котам
        1. Имя цели: "Еженедельная закупка корма котам"
        2. Ещё поля цели
    2. Объём бюджета: 5 000
    3. Категории: [ "Котейшества", "Мурлыки", "Вкусняшки" ]
    4. Приоритет (от 1 до 10 с восходящим значением): 10
    7. Тип бюджета (возможно свойства цели)
        1. Тип: периодический
        2. cron: 0 0 * * 0
    8. Счета: [ "Альфабанк", "Deutchebank" (надеюсь в скором будущем) ]
2. Отдых в Карелии
    1. Цель: Отдых в Карелии
        1. Имя цели: "Отдых в Карелии"
        2. Ещё поля цели
    2. Объём бюджета: 40 000
    3. Категории: [ "Отдых", "Карелия" ]
    4. Приоритет (от 1 до 10 с восходящим значением): 5
    5. Тип бюджета (возможно свойства цели)
        1. Тип: единоразовый
    6. Счета: [ "Сбербанк", "Банк Ворота Севера" {даже так :)} ]
3. Погашение кредита
    1. Цель: Погашение кредита
        1. Имя цели: "Погашение кредита"
        2. Ещё поля цели
    2. Объём бюджета: 50 000
    3. Категории: [ "Кредиты" ]
    4. Приоритет (от 1 до 10 с восходящим значением): 10
    5. Тип бюджета (возможно свойства цели)
        1. Тип: единоразовый
    6. Счета: [ "Сбербанк", "Максибанк" ]

Каждая запись со своим номером применяется к соответсвующему бюджету:

* 1 -> 1
* 2 -> 2
* 3 -> 3

Из каждого соответсвующего бюджета минусуется его баланс.

Счета в приложении представляют из себя проявление реальных счетов в банках. К слову, "счёт" в банке это базовая сущность.
Любая карта - будь то дебетовая или кредитная являются лишь интерфейсом к тому или иному счёту.
Дебетовая карта это обычный счёт, достояние на котором реально.
Кредитная карта привязана к кредитному счёту, достояние на котором взято в долг у банка.
Сумма денег на этом счету, это фактически "лимит" кредитной карты.

Бюджеты это более абстрактные сущности вроде "обещанного куска пирога" некоторой "цели". Цели и бюджеты связаны соотношением один к одному.
Цель бюджета является неким преобритением, потребностью или инвестицией, требующими финансирование.
Бюджет может быть единоразовым или периодичным. Так же у бюджета есть категория важности.
Бюджет представляется в виде свиньи копилки (что можно отобразить в графическом интерфейсе), реализация бюджета, это акт разбития этой свиньи.

У приложения будет механизм взаимодействия с банками, для выборки последних транзакция. Обычно интеграция с банком происходит по запросу от приложения,
хотя иногда можно настроить и колбек от банка, где банк будет сообщать о транзакциях. Но мы сосредоточимся на первом варианте, и будем
опрашивать банки. Для этого стоит создать небольшой эмулятор банка, который будет передавать приложению последние события со счетами данного пользователя.
Это позволит построить колоссальную систему тестирования приложения. Через этот же механизм будут приходить и состояния счетов пользователя.

На экране системы, пользователь сможет добавить счета и связать их с банками. С другой стороны, пользователь сможет создать бюджет с определённой целью.
Примеры бюджетов описаны выше.

**Comment by sshiae** [comment]
Круто описание!!
