### ISSUE TITLE
Сделать Hello World фронтенд

### ISSUE THREAD

**Issue by AAKVAS** [ITOneNorthGateVologda/.github#18]
Сделать пустой проект для фронтенда, чтобы далее развернуть на хостинге и настроить CI/CD

**Comment by olgapshen** [comment]
Я предлагаю сейчас сделать репозиторий, дабы вдохновить Витю @lvapl начать делать сюда коммиты :)

**Comment by olgapshen** [comment]
Так, вот тут я сделаю HelloWorld: https://github.com/ITOneNorthGateVologda/frontend
