### ISSUE TITLE
Реализация функционала авторизации и регистрации

### ISSUE THREAD

**Issue by sshiae** [ITOneNorthGateVologda/.github#4]
Функционал входа и регистрации позволит пользователям создать учетную запись и войти в систему для доступа к своим личным финансам. После успешной аутентификации пользователь будет перенаправлен на главную страницу приложения.

Регистрацию и авторизацию пока что делаем максимально простую, если будет в условиях то, какая авторизация и регистрацию должна быть, то адаптируем к условиям. Предлагаю пока что делать авторизацию и регистрацию максимально простую по логину и паролю, без всяких JWT токенов.

Авторизированным пользователям доступны будут все endpoints в системе, неавторизированным пользователям только endpoint для авторизации и регистрации.

https://spring.io/guides/gs/securing-web

```java
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "users")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true)
    private String username;

    private String password;

    // Другие поля пользователя (имя, email и т.д.)

    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL)
    private List<Account> accounts;
}
```

Создать отдельный `AuthenticationController` для авторизации и регистрации.

<h3>1. Регистрация пользователя</h3>

<h3>Endpoint URL</h3>

```curl
POST /api/v1/register
```

<h3>Описание</h3>

Этот endpoint позволяет регистрировать пользователей.

<h3>Параметры запроса</h3>

- `Тело запроса:` должно содержать информацию о новом пользователе.

<h3>Пример тела запроса</h3>

```json
{
    "username": "example_user",
    "password": "example_password"
    // Другие поля
}
```

<h3>Ответ</h3>

В качестве успешного ответа отправляется сообщение об успешной регистрации, если что то пошло не так, то там уже продумываем соответствующие коды и сообщения

```json
{
    "message": "Пользователь успешно зарегистрирован."
}
```

<h3>2. Аутентификация пользователя</h3>

<h3>Endpoint URL</h3>

```curl
POST /api/v1/login
```

<h3>Описание</h3>

Этот endpoint позволяет авторизировать пользователей в системе.

<h3>Параметры запроса</h3>

- `Тело запроса:` содержит учетные данные пользователя (пароль и логин).

<h3>Пример тела запроса</h3>

```json
{
    "username": "example_user",
    "password": "example_password"
}
```

<h3>Ответ</h3>

В качестве успешного ответа отправляется сообщение об успешной авторизации

```json
{
    "message": "Аутентификация успешна."
}
```

**Comment by olgapshen** [comment]
Так, тут если ты keycloak поднимаешь, то как видно это уже не актуально? Или может лучше не заморачиваться с keycloak и сделать в ручную через собственный API?

**Comment by olgapshen** [comment]
Так, договорились пока без keycloak, и что Тёма реализует авторизацию.

**Comment by sshiae** [comment]
Авторизацию и регистрацию реализовал, все задокументировал и выложил в репозитории https://github.com/ITOneNorthGateVologda/backend
