### ISSUE TITLE
Реализация функционала отслеживания расходов

### ISSUE THREAD

**Issue by sshiae** [ITOneNorthGateVologda/.github#5]
Функция, позволяющая пользователям записывать свои финансовые транзакции и отслеживать, куда уходят их деньги. Также должна быть возможность удалять расходы и редактировать их. Форма ввода расходов должна содержать поля для ввода суммы, категории расхода, даты и дополнительного комментария.

```java
@Entity
@Table(name = "transactions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "amount", nullable = false)
    private Double amount;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private TransactionCategory category;

    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "date", nullable = false)
    private Date date;

    @Column(name = "comment")
    private String comment;
}
```

Категории будем хранить как справочная информация отдельно:
```java
@Entity
@Table(name = "transaction_categories")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class TransactionCategory {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "name", nullable = false, unique = true)
    private String name;

    @OneToMany(mappedBy = "category", fetch = FetchType.LAZY)
    private Set<Transaction> transactions;
}
```

Создать отдельный `TransactionController` для работы с расходами.

<h3>1. Добавление расхода</h3>

<h3>Endpoint URL</h3>

```curl
POST /api/v1/users/{userId}/accounts/{accountId}/transactions
```

<h3>Описание</h3>

Этот endpoint позволяет добавить новую транзакцию (расход) для указанного пользователя и счета.

<h3>Параметры запроса</h3>

- `userId`: идентификатор пользователя, которому будет добавлен расход.
- `accountId`: идентификатор счета, на который будет добавлен расход.
- `Тело запроса:` должно содержать информацию о новой транзакции в формате JSON.

<h3>Пример тела запроса</h3>

```json
{
    "amount": 50.0,
    "category": {
        "id": 1
    },
    "date": "2024-04-30T12:00:00",
    "comment": "Покупка продуктов"
}
```

<h3>Ответ</h3>

В качестве ответа отправляется добавленный расход

```json
{
    "id": 1,
    "amount": 50.0,
    "category": {
        "id": 1,
        "name": "Продукты"
    },
    "date": "2024-04-30T12:00:00",
    "comment": "Покупка продуктов"
}
```

<h3>2. Получение расходов пользователя</h3>

<h3>Endpoint URL</h3>

```curl
GET /api/v1/users/{userId}/accounts/{accountId}/transactions
```

<h3>Описание</h3>

Этот endpoint позволяет получить список всех транзакций (расходов) для указанного пользователя и счета.

<h3>Параметры запроса</h3>

- `userId:` идентификатор пользователя, чьи транзакции требуется получить.
- `accountId:` идентификатор счета, по которому требуется получить транзакции.

<h3>Пример запроса</h3>

```curl
GET /api/v1/users/123/accounts/456/transactions
```

<h3>Ответ</h3>

В качестве ответа отправляется список расходов пользователя по конкретному счету

```json
[
    {
        "id": 1,
        "amount": 50.0,
        "category": {
            "id": 1,
            "name": "Продукты"
        },
        "date": "2024-04-30T12:00:00",
        "comment": "Покупка продуктов"
    },
    {
        "id": 2,
        "amount": 30.0,
        "category": {
            "id": 2,
            "name": "Транспорт"
        },
        "date": "2024-04-29T08:00:00",
        "comment": "Такси до работы"
    }
]
```

<h3>3. Редактирование расхода</h3>

<h3>Endpoint URL</h3>

```curl
PUT /api/v1/users/{userId}/accounts/{accountId}/transactions/{transactionId}
```

<h3>Описание</h3>

Этот endpoint позволяет обновить существующую транзакцию (расход) для указанного пользователя, счета и транзакции.

<h3>Параметры запроса</h3>

- `userId:` идентификатор пользователя, чья транзакция обновляется.
- `accountId:` идентификатор счета, на котором транзакция обновляется.
- `transactionId:` идентификатор транзакции, которая обновляется.
- `Тело запроса:` должно содержать обновленные данные транзакции в формате JSON.

<h3>Пример тела запроса</h3>

```json
{
    "amount": 75.0,
    "category": {
        "id": 1
    },
    "date": "2024-04-30T12:00:00",
    "comment": "Обновленная покупка продуктов"
}
```

<h3>Ответ</h3>

В качестве ответа отправляется обновленный расход

```json
{
    "id": 1,
    "amount": 75.0,
    "category": {
        "id": 1,
        "name": "Продукты"
    },
    "date": "2024-04-30T12:00:00",
    "comment": "Обновленная покупка продуктов"
}
```

<h3>4. Удаление расхода</h3>

<h3>Endpoint URL</h3>

```curl
DELETE /api/v1/users/{userId}/accounts/{accountId}/transactions/{transactionId}
```

<h3>Описание</h3>

Этот endpoint позволяет удалить существующую транзакцию (расход) для указанного пользователя, счета и транзакции.

<h3>Параметры запроса</h3>

- `userId:` идентификатор пользователя, чья транзакция удаляется.
- `accountId:` идентификатор счета, на котором транзакция удаляется.
- `transactionId:` идентификатор транзакции, которая удаляется.

<h3>Пример запроса</h3>

```curl
DELETE /api/v1/users/123/accounts/456/transactions/789
```

<h3>Ответ</h3>

```json
{
    "message": "Transaction deleted successfully."
}
```

**Comment by AAKVAS** [comment]
Сформировал новую задачу https://github.com/orgs/ITOneNorthGateVologda/projects/1/views/1?pane=issue&itemId=62315113

**Comment by olgapshen** [comment]
Не забывайте в таких случаях, ставить лейбочку `duplicate`
