### ISSUE TITLE
Реализация функционала по работе со счетами

### ISSUE THREAD

**Issue by sshiae** [ITOneNorthGateVologda/.github#6]
Пользователи могут создавать и называть счета, по котором будут проходить финансовые потоки. Можно, например, разделить наличность и средства на банковских картах по разных счетам. К примеру, можно создать счет, указать планируемые траты, к примеру, для создания какого - либо проекта. И в этот счет записывать все транзакции, можно отслеживать, насколько ожидаемые траты совпадают с фактическими. Можно записывать как доходы, так и расходы. Траты записываются по категориям.

Создать отдельный `AccountController` для работы с расходами.

<h3>1. Создание счета</h3>

<h3>Endpoint URL</h3>

```curl
POST /api/v1/users/{userId}/accounts
```

<h3>Описание</h3>

Этот endpoint позволяет добавить новый счет для пользователя

<h3>Параметры запроса</h3>

- `userId` - ID пользователя, для которого создается счет.
- `Тело запроса:` JSON представление нового счета.

<h3>Пример тела запроса</h3>

```json
{
    "name": "Проект X",
    "description": "Счет для проекта X",
    "plannedExpenses": 5000.0
}
```

<h3>Ответ</h3>

В качестве ответа возвращается добавленный счет

```json
{
    "id": 101,
    "name": "Проект X",
    "description": "Счет для проекта X",
    "plannedExpenses": 5000.0,
    "balance": 0.0
}
```

<h3>2. Получение списка счетов пользователя</h3>

<h3>Endpoint URL</h3>

```curl
GET /api/v1/users/{userId}/accounts
```

<h3>Описание</h3>

Этот endpoint позволяет получить список всех счетов конкретного пользователя

<h3>Параметры запроса</h3>

- `userId` - ID пользователя

<h3>Ответ</h3>

В качестве ответа возвращается список счетов

```json
[
    {
        "id": 101,
        "name": "Проект X",
        "description": "Счет для проекта X",
        "plannedExpenses": 5000.0,
        "balance": 0.0
    },
    {
        "id": 102,
        "name": "Отпуск",
        "description": "Счет для отпуска",
        "plannedExpenses": 2000.0,
        "balance": 500.0
    }
]
```

<h3>3. Обновление счета</h3>

<h3>Endpoint URL</h3>

```curl
PUT /api/v1/users/{userId}/accounts/{accountId}
```

<h3>Описание</h3>

Этот endpoint позволяет обновить существующий счет

<h3>Параметры запроса</h3>

- `userId:` - ID пользователя.
- `accountId:` - ID счета, который обновляется.
- `Тело запроса:` JSON представление обновленных данных счета.

<h3>Пример тела запроса</h3>

```json
{
    "name": "Новое название счета",
    "description": "Новое описание счета",
    "plannedExpenses": 6000.0
}
```

<h3>Ответ</h3>

В качестве ответа возвращается обновленный счет

```json
{
    "id": 101,
    "name": "Новое название счета",
    "description": "Новое описание счета",
    "plannedExpenses": 6000.0,
    "balance": 0.0
}
```

<h3>4. Удаление счета</h3>

<h3>Endpoint URL</h3>

```curl
DELETE /api/v1/users/{userId}/accounts/{accountId}
```

<h3>Описание</h3>

Этот endpoint позволяет удалить существующий счет у пользователя

<h3>Параметры запроса</h3>

- `userId:` - ID пользователя.
- `accountId:` - ID счета, который удаляется.

<h3>Ответ</h3>

```json
{
    "message": "Счет успешно удален."
}
```

**Comment by olgapshen** [comment]
Так, тут в принцпе остаётся всё так же кроме "plannedExpenses", если я не ошибаюсь.

**Comment by sshiae** [comment]
Создали новую задачу https://github.com/ITOneNorthGateVologda/backend/issues/5, эту закрываю

**Comment by olgapshen** [comment]
Не забывайте в таких случаях, ставить лейбочку `duplicate`.
